### ISSUE TITLE
element ID avoid collision

### ISSUE THREAD

**Issue by balaji-b-v** [egarbarino/svelte-todo#1]
Hi @egarbarino , Please suggest the way out of this repeated element ID..

Does the ShadowDOM v1 used by svelte have any mechanism to handle this?

![multipleIDinHTML](https://user-images.githubusercontent.com/3445541/79466200-e30c6700-8019-11ea-84e4-42bd80f5a699.png)

**Comment by balaji-b-v** [comment]
Self answering:
1. Usually such scenario is NOT seen.
2. "id" will never be used in a web component or for that matter in any "Foundational component" that becomes part of larger "Application Component"[eg input element being part of a form Component].

Please suggest your thoughts on the above...

**Comment by egarbarino** [comment]
Hi Balaji,

Actually, such a scenario is quite common. The whole reason of declaring components is to be able to instantiate them many times over. The problem is not Svelte's but my own example. I had explicitly set the id="description" on a component that may not necessarily be unique. 

Before:
``` html
<!-- BEFORE -->
<input type="text" id="description" bind:value={item}/>

<!-- NOW -->
<input type="text" bind:value={item}/>
```

I have patched it so thanks for identifying this bug :)
